# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: adjustment_and_triggering_of_portfolio.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='adjustment_and_triggering_of_portfolio.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n,adjustment_and_triggering_of_portfolio.proto\"0\n\x0ePortFolioInput\x12\r\n\x05price\x18\x01 \x01(\t\x12\x0f\n\x07setting\x18\x02 \x01(\x02\" \n\x0fPortFolioOutput\x12\r\n\x05value\x18\x01 \x01(\x08\x32\xcb\x01\n\"AdjustmentAndTriggeringOfPortfolio\x12\x33\n\x0cPortFolioVar\x12\x0f.PortFolioInput\x1a\x10.PortFolioOutput\"\x00\x12:\n\x13PortfolioVolatility\x12\x0f.PortFolioInput\x1a\x10.PortFolioOutput\"\x00\x12\x34\n\rPortfolioDiff\x12\x0f.PortFolioInput\x1a\x10.PortFolioOutput\"\x00\x62\x06proto3')
)




_PORTFOLIOINPUT = _descriptor.Descriptor(
  name='PortFolioInput',
  full_name='PortFolioInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='price', full_name='PortFolioInput.price', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='setting', full_name='PortFolioInput.setting', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=96,
)


_PORTFOLIOOUTPUT = _descriptor.Descriptor(
  name='PortFolioOutput',
  full_name='PortFolioOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='PortFolioOutput.value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=130,
)

DESCRIPTOR.message_types_by_name['PortFolioInput'] = _PORTFOLIOINPUT
DESCRIPTOR.message_types_by_name['PortFolioOutput'] = _PORTFOLIOOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PortFolioInput = _reflection.GeneratedProtocolMessageType('PortFolioInput', (_message.Message,), {
  'DESCRIPTOR' : _PORTFOLIOINPUT,
  '__module__' : 'adjustment_and_triggering_of_portfolio_pb2'
  # @@protoc_insertion_point(class_scope:PortFolioInput)
  })
_sym_db.RegisterMessage(PortFolioInput)

PortFolioOutput = _reflection.GeneratedProtocolMessageType('PortFolioOutput', (_message.Message,), {
  'DESCRIPTOR' : _PORTFOLIOOUTPUT,
  '__module__' : 'adjustment_and_triggering_of_portfolio_pb2'
  # @@protoc_insertion_point(class_scope:PortFolioOutput)
  })
_sym_db.RegisterMessage(PortFolioOutput)



_ADJUSTMENTANDTRIGGERINGOFPORTFOLIO = _descriptor.ServiceDescriptor(
  name='AdjustmentAndTriggeringOfPortfolio',
  full_name='AdjustmentAndTriggeringOfPortfolio',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=133,
  serialized_end=336,
  methods=[
  _descriptor.MethodDescriptor(
    name='PortFolioVar',
    full_name='AdjustmentAndTriggeringOfPortfolio.PortFolioVar',
    index=0,
    containing_service=None,
    input_type=_PORTFOLIOINPUT,
    output_type=_PORTFOLIOOUTPUT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PortfolioVolatility',
    full_name='AdjustmentAndTriggeringOfPortfolio.PortfolioVolatility',
    index=1,
    containing_service=None,
    input_type=_PORTFOLIOINPUT,
    output_type=_PORTFOLIOOUTPUT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PortfolioDiff',
    full_name='AdjustmentAndTriggeringOfPortfolio.PortfolioDiff',
    index=2,
    containing_service=None,
    input_type=_PORTFOLIOINPUT,
    output_type=_PORTFOLIOOUTPUT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ADJUSTMENTANDTRIGGERINGOFPORTFOLIO)

DESCRIPTOR.services_by_name['AdjustmentAndTriggeringOfPortfolio'] = _ADJUSTMENTANDTRIGGERINGOFPORTFOLIO

# @@protoc_insertion_point(module_scope)
