# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import rpc.protoc.citibank_api_pb2 as citibank__api__pb2


class CitibankApiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.StockPoundage = channel.unary_unary(
        '/CitibankApi/StockPoundage',
        request_serializer=citibank__api__pb2.StockPoundageInput.SerializeToString,
        response_deserializer=citibank__api__pb2.StockPoundageOutput.FromString,
        )
    self.FuturePoundage = channel.unary_unary(
        '/CitibankApi/FuturePoundage',
        request_serializer=citibank__api__pb2.FuturePoundageInput.SerializeToString,
        response_deserializer=citibank__api__pb2.FuturePoundageOutput.FromString,
        )
    self.OptionsPoundage = channel.unary_unary(
        '/CitibankApi/OptionsPoundage',
        request_serializer=citibank__api__pb2.OptionsPoundageInput.SerializeToString,
        response_deserializer=citibank__api__pb2.OptionsPoundageOutput.FromString,
        )


class CitibankApiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def StockPoundage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FuturePoundage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def OptionsPoundage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CitibankApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'StockPoundage': grpc.unary_unary_rpc_method_handler(
          servicer.StockPoundage,
          request_deserializer=citibank__api__pb2.StockPoundageInput.FromString,
          response_serializer=citibank__api__pb2.StockPoundageOutput.SerializeToString,
      ),
      'FuturePoundage': grpc.unary_unary_rpc_method_handler(
          servicer.FuturePoundage,
          request_deserializer=citibank__api__pb2.FuturePoundageInput.FromString,
          response_serializer=citibank__api__pb2.FuturePoundageOutput.SerializeToString,
      ),
      'OptionsPoundage': grpc.unary_unary_rpc_method_handler(
          servicer.OptionsPoundage,
          request_deserializer=citibank__api__pb2.OptionsPoundageInput.FromString,
          response_serializer=citibank__api__pb2.OptionsPoundageOutput.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'CitibankApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
