# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: citibank_api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='citibank_api.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12\x63itibank_api.proto2\r\n\x0b\x43itibankApib\x06proto3')
)



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CITIBANKAPI = _descriptor.ServiceDescriptor(
  name='CitibankApi',
  full_name='CitibankApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=22,
  serialized_end=35,
  methods=[
])
_sym_db.RegisterServiceDescriptor(_CITIBANKAPI)

DESCRIPTOR.services_by_name['CitibankApi'] = _CITIBANKAPI

# @@protoc_insertion_point(module_scope)
