# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: citibank_api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='citibank_api.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n\037com.example.ffbackend.rpc.protoB\020CitibankApiProto'),
  serialized_pb=_b('\n\x12\x63itibank_api.proto\")\n\x12StockPoundageInput\x12\x13\n\x0b\x64\x65\x61l_amount\x18\x01 \x01(\x02\"$\n\x13StockPoundageOutput\x12\r\n\x05value\x18\x01 \x01(\x02\"*\n\x13\x46uturePoundageInput\x12\x13\n\x0b\x64\x65\x61l_amount\x18\x01 \x01(\x02\"%\n\x14\x46uturePoundageOutput\x12\r\n\x05value\x18\x01 \x01(\x02\",\n\x14OptionsPoundageInput\x12\x14\n\x0cnum_of_piece\x18\x01 \x01(\x05\"&\n\x15OptionsPoundageOutput\x12\r\n\x05value\x18\x01 \x01(\x02\x32\xd0\x01\n\x0b\x43itibankApi\x12<\n\rStockPoundage\x12\x13.StockPoundageInput\x1a\x14.StockPoundageOutput\"\x00\x12?\n\x0e\x46uturePoundage\x12\x14.FuturePoundageInput\x1a\x15.FuturePoundageOutput\"\x00\x12\x42\n\x0fOptionsPoundage\x12\x15.OptionsPoundageInput\x1a\x16.OptionsPoundageOutput\"\x00\x42\x33\n\x1f\x63om.example.ffbackend.rpc.protoB\x10\x43itibankApiProtob\x06proto3')
)




_STOCKPOUNDAGEINPUT = _descriptor.Descriptor(
  name='StockPoundageInput',
  full_name='StockPoundageInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deal_amount', full_name='StockPoundageInput.deal_amount', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=63,
)


_STOCKPOUNDAGEOUTPUT = _descriptor.Descriptor(
  name='StockPoundageOutput',
  full_name='StockPoundageOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='StockPoundageOutput.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=101,
)


_FUTUREPOUNDAGEINPUT = _descriptor.Descriptor(
  name='FuturePoundageInput',
  full_name='FuturePoundageInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deal_amount', full_name='FuturePoundageInput.deal_amount', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=145,
)


_FUTUREPOUNDAGEOUTPUT = _descriptor.Descriptor(
  name='FuturePoundageOutput',
  full_name='FuturePoundageOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='FuturePoundageOutput.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=184,
)


_OPTIONSPOUNDAGEINPUT = _descriptor.Descriptor(
  name='OptionsPoundageInput',
  full_name='OptionsPoundageInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_of_piece', full_name='OptionsPoundageInput.num_of_piece', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=230,
)


_OPTIONSPOUNDAGEOUTPUT = _descriptor.Descriptor(
  name='OptionsPoundageOutput',
  full_name='OptionsPoundageOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='OptionsPoundageOutput.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=270,
)

DESCRIPTOR.message_types_by_name['StockPoundageInput'] = _STOCKPOUNDAGEINPUT
DESCRIPTOR.message_types_by_name['StockPoundageOutput'] = _STOCKPOUNDAGEOUTPUT
DESCRIPTOR.message_types_by_name['FuturePoundageInput'] = _FUTUREPOUNDAGEINPUT
DESCRIPTOR.message_types_by_name['FuturePoundageOutput'] = _FUTUREPOUNDAGEOUTPUT
DESCRIPTOR.message_types_by_name['OptionsPoundageInput'] = _OPTIONSPOUNDAGEINPUT
DESCRIPTOR.message_types_by_name['OptionsPoundageOutput'] = _OPTIONSPOUNDAGEOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StockPoundageInput = _reflection.GeneratedProtocolMessageType('StockPoundageInput', (_message.Message,), dict(
  DESCRIPTOR = _STOCKPOUNDAGEINPUT,
  __module__ = 'citibank_api_pb2'
  # @@protoc_insertion_point(class_scope:StockPoundageInput)
  ))
_sym_db.RegisterMessage(StockPoundageInput)

StockPoundageOutput = _reflection.GeneratedProtocolMessageType('StockPoundageOutput', (_message.Message,), dict(
  DESCRIPTOR = _STOCKPOUNDAGEOUTPUT,
  __module__ = 'citibank_api_pb2'
  # @@protoc_insertion_point(class_scope:StockPoundageOutput)
  ))
_sym_db.RegisterMessage(StockPoundageOutput)

FuturePoundageInput = _reflection.GeneratedProtocolMessageType('FuturePoundageInput', (_message.Message,), dict(
  DESCRIPTOR = _FUTUREPOUNDAGEINPUT,
  __module__ = 'citibank_api_pb2'
  # @@protoc_insertion_point(class_scope:FuturePoundageInput)
  ))
_sym_db.RegisterMessage(FuturePoundageInput)

FuturePoundageOutput = _reflection.GeneratedProtocolMessageType('FuturePoundageOutput', (_message.Message,), dict(
  DESCRIPTOR = _FUTUREPOUNDAGEOUTPUT,
  __module__ = 'citibank_api_pb2'
  # @@protoc_insertion_point(class_scope:FuturePoundageOutput)
  ))
_sym_db.RegisterMessage(FuturePoundageOutput)

OptionsPoundageInput = _reflection.GeneratedProtocolMessageType('OptionsPoundageInput', (_message.Message,), dict(
  DESCRIPTOR = _OPTIONSPOUNDAGEINPUT,
  __module__ = 'citibank_api_pb2'
  # @@protoc_insertion_point(class_scope:OptionsPoundageInput)
  ))
_sym_db.RegisterMessage(OptionsPoundageInput)

OptionsPoundageOutput = _reflection.GeneratedProtocolMessageType('OptionsPoundageOutput', (_message.Message,), dict(
  DESCRIPTOR = _OPTIONSPOUNDAGEOUTPUT,
  __module__ = 'citibank_api_pb2'
  # @@protoc_insertion_point(class_scope:OptionsPoundageOutput)
  ))
_sym_db.RegisterMessage(OptionsPoundageOutput)


DESCRIPTOR._options = None

_CITIBANKAPI = _descriptor.ServiceDescriptor(
  name='CitibankApi',
  full_name='CitibankApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=273,
  serialized_end=481,
  methods=[
  _descriptor.MethodDescriptor(
    name='StockPoundage',
    full_name='CitibankApi.StockPoundage',
    index=0,
    containing_service=None,
    input_type=_STOCKPOUNDAGEINPUT,
    output_type=_STOCKPOUNDAGEOUTPUT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FuturePoundage',
    full_name='CitibankApi.FuturePoundage',
    index=1,
    containing_service=None,
    input_type=_FUTUREPOUNDAGEINPUT,
    output_type=_FUTUREPOUNDAGEOUTPUT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='OptionsPoundage',
    full_name='CitibankApi.OptionsPoundage',
    index=2,
    containing_service=None,
    input_type=_OPTIONSPOUNDAGEINPUT,
    output_type=_OPTIONSPOUNDAGEOUTPUT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CITIBANKAPI)

DESCRIPTOR.services_by_name['CitibankApi'] = _CITIBANKAPI

# @@protoc_insertion_point(module_scope)
