# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: conditional_trigger.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='conditional_trigger.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x19\x63onditional_trigger.proto\"I\n\x16StockTurnoverRateInput\x12\x12\n\nstock_code\x18\x01 \x01(\t\x12\x0b\n\x03top\x18\x02 \x01(\x02\x12\x0e\n\x06\x62ottom\x18\x03 \x01(\x02\"(\n\x17StockTurnoverRateOutput\x12\r\n\x05value\x18\x01 \x01(\x08\"A\n\x0eStockMacdInput\x12\x12\n\nstock_code\x18\x01 \x01(\t\x12\x0b\n\x03top\x18\x02 \x01(\x02\x12\x0e\n\x06\x62ottom\x18\x03 \x01(\x02\" \n\x0fStockMacdOutput\x12\r\n\x05value\x18\x02 \x01(\x08\"R\n\rStockRsiInput\x12\x12\n\nstock_code\x18\x01 \x01(\t\x12\x10\n\x08rsi_time\x18\x02 \x01(\x05\x12\x0b\n\x03top\x18\x03 \x01(\x02\x12\x0e\n\x06\x62ottom\x18\x04 \x01(\x02\"\x1f\n\x0eStockRsiOutput\x12\r\n\x05value\x18\x01 \x01(\x08\"D\n\rStockKdjInput\x12\x12\n\nstock_code\x18\x01 \x01(\t\x12\t\n\x01K\x18\x02 \x01(\x02\x12\t\n\x01\x44\x18\x03 \x01(\x02\x12\t\n\x01J\x18\x04 \x01(\x02\"\x1f\n\x0eStockKdjOutput\x12\r\n\x05value\x18\x01 \x01(\x08\"N\n\rStockRocInput\x12\x12\n\nstock_code\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\x05\x12\x0b\n\x03top\x18\x03 \x01(\x02\x12\x0e\n\x06\x62ottom\x18\x04 \x01(\x02\"\x1f\n\x0eStockRocOutput\x12\r\n\x05value\x18\x01 \x01(\x08\"7\n\x10StockSharpeInput\x12\x12\n\nstock_code\x18\x01 \x01(\t\x12\x0f\n\x07setting\x18\x02 \x01(\x02\"\"\n\x11StockSharpeOutput\x12\r\n\x05value\x18\x01 \x01(\x08\x32\xd5\x02\n\x12\x43onditionalTrigger\x12H\n\x11StockTurnoverRate\x12\x17.StockTurnoverRateInput\x1a\x18.StockTurnoverRateOutput\"\x00\x12\x30\n\tStockMacd\x12\x0f.StockMacdInput\x1a\x10.StockMacdOutput\"\x00\x12-\n\x08StockRsi\x12\x0e.StockRsiInput\x1a\x0f.StockRsiOutput\"\x00\x12-\n\x08StockKdj\x12\x0e.StockKdjInput\x1a\x0f.StockKdjOutput\"\x00\x12-\n\x08StockRoc\x12\x0e.StockRocInput\x1a\x0f.StockRocOutput\"\x00\x12\x36\n\x0bStockSharpe\x12\x11.StockSharpeInput\x1a\x12.StockSharpeOutput\"\x00\x62\x06proto3')
)




_STOCKTURNOVERRATEINPUT = _descriptor.Descriptor(
  name='StockTurnoverRateInput',
  full_name='StockTurnoverRateInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stock_code', full_name='StockTurnoverRateInput.stock_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='top', full_name='StockTurnoverRateInput.top', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bottom', full_name='StockTurnoverRateInput.bottom', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=102,
)


_STOCKTURNOVERRATEOUTPUT = _descriptor.Descriptor(
  name='StockTurnoverRateOutput',
  full_name='StockTurnoverRateOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='StockTurnoverRateOutput.value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=144,
)


_STOCKMACDINPUT = _descriptor.Descriptor(
  name='StockMacdInput',
  full_name='StockMacdInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stock_code', full_name='StockMacdInput.stock_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='top', full_name='StockMacdInput.top', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bottom', full_name='StockMacdInput.bottom', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=211,
)


_STOCKMACDOUTPUT = _descriptor.Descriptor(
  name='StockMacdOutput',
  full_name='StockMacdOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='StockMacdOutput.value', index=0,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=245,
)


_STOCKRSIINPUT = _descriptor.Descriptor(
  name='StockRsiInput',
  full_name='StockRsiInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stock_code', full_name='StockRsiInput.stock_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rsi_time', full_name='StockRsiInput.rsi_time', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='top', full_name='StockRsiInput.top', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bottom', full_name='StockRsiInput.bottom', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=329,
)


_STOCKRSIOUTPUT = _descriptor.Descriptor(
  name='StockRsiOutput',
  full_name='StockRsiOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='StockRsiOutput.value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=331,
  serialized_end=362,
)


_STOCKKDJINPUT = _descriptor.Descriptor(
  name='StockKdjInput',
  full_name='StockKdjInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stock_code', full_name='StockKdjInput.stock_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='K', full_name='StockKdjInput.K', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='D', full_name='StockKdjInput.D', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='J', full_name='StockKdjInput.J', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=364,
  serialized_end=432,
)


_STOCKKDJOUTPUT = _descriptor.Descriptor(
  name='StockKdjOutput',
  full_name='StockKdjOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='StockKdjOutput.value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=434,
  serialized_end=465,
)


_STOCKROCINPUT = _descriptor.Descriptor(
  name='StockRocInput',
  full_name='StockRocInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stock_code', full_name='StockRocInput.stock_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='StockRocInput.time', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='top', full_name='StockRocInput.top', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bottom', full_name='StockRocInput.bottom', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=467,
  serialized_end=545,
)


_STOCKROCOUTPUT = _descriptor.Descriptor(
  name='StockRocOutput',
  full_name='StockRocOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='StockRocOutput.value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=547,
  serialized_end=578,
)


_STOCKSHARPEINPUT = _descriptor.Descriptor(
  name='StockSharpeInput',
  full_name='StockSharpeInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stock_code', full_name='StockSharpeInput.stock_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='setting', full_name='StockSharpeInput.setting', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=580,
  serialized_end=635,
)


_STOCKSHARPEOUTPUT = _descriptor.Descriptor(
  name='StockSharpeOutput',
  full_name='StockSharpeOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='StockSharpeOutput.value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=637,
  serialized_end=671,
)

DESCRIPTOR.message_types_by_name['StockTurnoverRateInput'] = _STOCKTURNOVERRATEINPUT
DESCRIPTOR.message_types_by_name['StockTurnoverRateOutput'] = _STOCKTURNOVERRATEOUTPUT
DESCRIPTOR.message_types_by_name['StockMacdInput'] = _STOCKMACDINPUT
DESCRIPTOR.message_types_by_name['StockMacdOutput'] = _STOCKMACDOUTPUT
DESCRIPTOR.message_types_by_name['StockRsiInput'] = _STOCKRSIINPUT
DESCRIPTOR.message_types_by_name['StockRsiOutput'] = _STOCKRSIOUTPUT
DESCRIPTOR.message_types_by_name['StockKdjInput'] = _STOCKKDJINPUT
DESCRIPTOR.message_types_by_name['StockKdjOutput'] = _STOCKKDJOUTPUT
DESCRIPTOR.message_types_by_name['StockRocInput'] = _STOCKROCINPUT
DESCRIPTOR.message_types_by_name['StockRocOutput'] = _STOCKROCOUTPUT
DESCRIPTOR.message_types_by_name['StockSharpeInput'] = _STOCKSHARPEINPUT
DESCRIPTOR.message_types_by_name['StockSharpeOutput'] = _STOCKSHARPEOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StockTurnoverRateInput = _reflection.GeneratedProtocolMessageType('StockTurnoverRateInput', (_message.Message,), {
  'DESCRIPTOR' : _STOCKTURNOVERRATEINPUT,
  '__module__' : 'conditional_trigger_pb2'
  # @@protoc_insertion_point(class_scope:StockTurnoverRateInput)
  })
_sym_db.RegisterMessage(StockTurnoverRateInput)

StockTurnoverRateOutput = _reflection.GeneratedProtocolMessageType('StockTurnoverRateOutput', (_message.Message,), {
  'DESCRIPTOR' : _STOCKTURNOVERRATEOUTPUT,
  '__module__' : 'conditional_trigger_pb2'
  # @@protoc_insertion_point(class_scope:StockTurnoverRateOutput)
  })
_sym_db.RegisterMessage(StockTurnoverRateOutput)

StockMacdInput = _reflection.GeneratedProtocolMessageType('StockMacdInput', (_message.Message,), {
  'DESCRIPTOR' : _STOCKMACDINPUT,
  '__module__' : 'conditional_trigger_pb2'
  # @@protoc_insertion_point(class_scope:StockMacdInput)
  })
_sym_db.RegisterMessage(StockMacdInput)

StockMacdOutput = _reflection.GeneratedProtocolMessageType('StockMacdOutput', (_message.Message,), {
  'DESCRIPTOR' : _STOCKMACDOUTPUT,
  '__module__' : 'conditional_trigger_pb2'
  # @@protoc_insertion_point(class_scope:StockMacdOutput)
  })
_sym_db.RegisterMessage(StockMacdOutput)

StockRsiInput = _reflection.GeneratedProtocolMessageType('StockRsiInput', (_message.Message,), {
  'DESCRIPTOR' : _STOCKRSIINPUT,
  '__module__' : 'conditional_trigger_pb2'
  # @@protoc_insertion_point(class_scope:StockRsiInput)
  })
_sym_db.RegisterMessage(StockRsiInput)

StockRsiOutput = _reflection.GeneratedProtocolMessageType('StockRsiOutput', (_message.Message,), {
  'DESCRIPTOR' : _STOCKRSIOUTPUT,
  '__module__' : 'conditional_trigger_pb2'
  # @@protoc_insertion_point(class_scope:StockRsiOutput)
  })
_sym_db.RegisterMessage(StockRsiOutput)

StockKdjInput = _reflection.GeneratedProtocolMessageType('StockKdjInput', (_message.Message,), {
  'DESCRIPTOR' : _STOCKKDJINPUT,
  '__module__' : 'conditional_trigger_pb2'
  # @@protoc_insertion_point(class_scope:StockKdjInput)
  })
_sym_db.RegisterMessage(StockKdjInput)

StockKdjOutput = _reflection.GeneratedProtocolMessageType('StockKdjOutput', (_message.Message,), {
  'DESCRIPTOR' : _STOCKKDJOUTPUT,
  '__module__' : 'conditional_trigger_pb2'
  # @@protoc_insertion_point(class_scope:StockKdjOutput)
  })
_sym_db.RegisterMessage(StockKdjOutput)

StockRocInput = _reflection.GeneratedProtocolMessageType('StockRocInput', (_message.Message,), {
  'DESCRIPTOR' : _STOCKROCINPUT,
  '__module__' : 'conditional_trigger_pb2'
  # @@protoc_insertion_point(class_scope:StockRocInput)
  })
_sym_db.RegisterMessage(StockRocInput)

StockRocOutput = _reflection.GeneratedProtocolMessageType('StockRocOutput', (_message.Message,), {
  'DESCRIPTOR' : _STOCKROCOUTPUT,
  '__module__' : 'conditional_trigger_pb2'
  # @@protoc_insertion_point(class_scope:StockRocOutput)
  })
_sym_db.RegisterMessage(StockRocOutput)

StockSharpeInput = _reflection.GeneratedProtocolMessageType('StockSharpeInput', (_message.Message,), {
  'DESCRIPTOR' : _STOCKSHARPEINPUT,
  '__module__' : 'conditional_trigger_pb2'
  # @@protoc_insertion_point(class_scope:StockSharpeInput)
  })
_sym_db.RegisterMessage(StockSharpeInput)

StockSharpeOutput = _reflection.GeneratedProtocolMessageType('StockSharpeOutput', (_message.Message,), {
  'DESCRIPTOR' : _STOCKSHARPEOUTPUT,
  '__module__' : 'conditional_trigger_pb2'
  # @@protoc_insertion_point(class_scope:StockSharpeOutput)
  })
_sym_db.RegisterMessage(StockSharpeOutput)



_CONDITIONALTRIGGER = _descriptor.ServiceDescriptor(
  name='ConditionalTrigger',
  full_name='ConditionalTrigger',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=674,
  serialized_end=1015,
  methods=[
  _descriptor.MethodDescriptor(
    name='StockTurnoverRate',
    full_name='ConditionalTrigger.StockTurnoverRate',
    index=0,
    containing_service=None,
    input_type=_STOCKTURNOVERRATEINPUT,
    output_type=_STOCKTURNOVERRATEOUTPUT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StockMacd',
    full_name='ConditionalTrigger.StockMacd',
    index=1,
    containing_service=None,
    input_type=_STOCKMACDINPUT,
    output_type=_STOCKMACDOUTPUT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StockRsi',
    full_name='ConditionalTrigger.StockRsi',
    index=2,
    containing_service=None,
    input_type=_STOCKRSIINPUT,
    output_type=_STOCKRSIOUTPUT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StockKdj',
    full_name='ConditionalTrigger.StockKdj',
    index=3,
    containing_service=None,
    input_type=_STOCKKDJINPUT,
    output_type=_STOCKKDJOUTPUT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StockRoc',
    full_name='ConditionalTrigger.StockRoc',
    index=4,
    containing_service=None,
    input_type=_STOCKROCINPUT,
    output_type=_STOCKROCOUTPUT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StockSharpe',
    full_name='ConditionalTrigger.StockSharpe',
    index=5,
    containing_service=None,
    input_type=_STOCKSHARPEINPUT,
    output_type=_STOCKSHARPEOUTPUT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONDITIONALTRIGGER)

DESCRIPTOR.services_by_name['ConditionalTrigger'] = _CONDITIONALTRIGGER

# @@protoc_insertion_point(module_scope)
