# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drawing.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='drawing.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rdrawing.proto2\t\n\x07\x44rawingb\x06proto3')
)



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_DRAWING = _descriptor.ServiceDescriptor(
  name='Drawing',
  full_name='Drawing',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=17,
  serialized_end=26,
  methods=[
])
_sym_db.RegisterServiceDescriptor(_DRAWING)

DESCRIPTOR.services_by_name['Drawing'] = _DRAWING

# @@protoc_insertion_point(module_scope)
