# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc



class OptionFuturesStub(object):
  """=========================================================
  期权部分函数文档
  =========================================================
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """


class OptionFuturesServicer(object):
  """=========================================================
  期权部分函数文档
  =========================================================
  """


def add_OptionFuturesServicer_to_server(servicer, server):
  rpc_method_handlers = {
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'OptionFutures', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
