# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import rpc.protoc.option_futures_pb2 as option__futures__pb2


class OptionFuturesStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.PortfolioDelta = channel.unary_unary(
        '/OptionFutures/PortfolioDelta',
        request_serializer=option__futures__pb2.PortfolioDeltaInput.SerializeToString,
        response_deserializer=option__futures__pb2.PortfolioDeltaOutput.FromString,
        )
    self.PortfolioGamma = channel.unary_unary(
        '/OptionFutures/PortfolioGamma',
        request_serializer=option__futures__pb2.PortfolioGammaInput.SerializeToString,
        response_deserializer=option__futures__pb2.PortfolioGammaOutput.FromString,
        )
    self.PortfolioVega = channel.unary_unary(
        '/OptionFutures/PortfolioVega',
        request_serializer=option__futures__pb2.PortfolioVegaInput.SerializeToString,
        response_deserializer=option__futures__pb2.PortfolioVegaOutput.FromString,
        )
    self.PortfolioTheta = channel.unary_unary(
        '/OptionFutures/PortfolioTheta',
        request_serializer=option__futures__pb2.PortfolioThetaInput.SerializeToString,
        response_deserializer=option__futures__pb2.PortfolioThetaOutput.FromString,
        )
    self.PortfolioRho = channel.unary_unary(
        '/OptionFutures/PortfolioRho',
        request_serializer=option__futures__pb2.PortfolioRhoInput.SerializeToString,
        response_deserializer=option__futures__pb2.PortfolioRhoOutput.FromString,
        )
    self.PortfolioVolatility = channel.unary_unary(
        '/OptionFutures/PortfolioVolatility',
        request_serializer=option__futures__pb2.PortfolioVolatilityInput.SerializeToString,
        response_deserializer=option__futures__pb2.PortfolioVolatilityOutput.FromString,
        )
    self.PortfolioEarningRate = channel.unary_unary(
        '/OptionFutures/PortfolioEarningRate',
        request_serializer=option__futures__pb2.PortfolioEarningRateInput.SerializeToString,
        response_deserializer=option__futures__pb2.PortfolioEarningRateOutput.FromString,
        )
    self.RetrainDeltaModel = channel.unary_unary(
        '/OptionFutures/RetrainDeltaModel',
        request_serializer=option__futures__pb2.RetrainDeltaModelInput.SerializeToString,
        response_deserializer=option__futures__pb2.RetrainDeltaModelOutput.FromString,
        )
    self.RetrainGammaModel = channel.unary_unary(
        '/OptionFutures/RetrainGammaModel',
        request_serializer=option__futures__pb2.RetrainGammaModelInput.SerializeToString,
        response_deserializer=option__futures__pb2.RetrainGammaModelOutput.FromString,
        )
    self.FitDelta = channel.unary_unary(
        '/OptionFutures/FitDelta',
        request_serializer=option__futures__pb2.FitDeltaInput.SerializeToString,
        response_deserializer=option__futures__pb2.FitDeltaOutput.FromString,
        )
    self.FitGamma = channel.unary_unary(
        '/OptionFutures/FitGamma',
        request_serializer=option__futures__pb2.FitGammaInput.SerializeToString,
        response_deserializer=option__futures__pb2.FitGammaOutput.FromString,
        )
    self.CalOptionAmt = channel.unary_unary(
        '/OptionFutures/CalOptionAmt',
        request_serializer=option__futures__pb2.CalOptionAmtInput.SerializeToString,
        response_deserializer=option__futures__pb2.CalOptionAmtOutput.FromString,
        )
    self.GenerateRecommendOptionDelta = channel.unary_unary(
        '/OptionFutures/GenerateRecommendOptionDelta',
        request_serializer=option__futures__pb2.GenerateRecommendOptionDeltaInput.SerializeToString,
        response_deserializer=option__futures__pb2.GenerateRecommendOptionDeltaOutput.FromString,
        )
    self.GenerateRecommendOptionGamma = channel.unary_unary(
        '/OptionFutures/GenerateRecommendOptionGamma',
        request_serializer=option__futures__pb2.GenerateRecommendOptionGammaInput.SerializeToString,
        response_deserializer=option__futures__pb2.GenerateRecommendOptionGammaOutput.FromString,
        )
    self.PortfolioBeta = channel.unary_unary(
        '/OptionFutures/PortfolioBeta',
        request_serializer=option__futures__pb2.PortfolioBetaInput.SerializeToString,
        response_deserializer=option__futures__pb2.PortfolioBetaOutput.FromString,
        )
    self.RetrainBetaModel = channel.unary_unary(
        '/OptionFutures/RetrainBetaModel',
        request_serializer=option__futures__pb2.RetrainBetaModelInput.SerializeToString,
        response_deserializer=option__futures__pb2.RetrainBetaModelOutput.FromString,
        )
    self.FitBeta = channel.unary_unary(
        '/OptionFutures/FitBeta',
        request_serializer=option__futures__pb2.FitBetaInput.SerializeToString,
        response_deserializer=option__futures__pb2.FitBetaOutput.FromString,
        )
    self.CalFutureAmt = channel.unary_unary(
        '/OptionFutures/CalFutureAmt',
        request_serializer=option__futures__pb2.CalFutureAmtInput.SerializeToString,
        response_deserializer=option__futures__pb2.CalFutureAmtOutput.FromString,
        )
    self.GenerateRecommendFuture = channel.unary_unary(
        '/OptionFutures/GenerateRecommendFuture',
        request_serializer=option__futures__pb2.GenerateRecommendFutureInput.SerializeToString,
        response_deserializer=option__futures__pb2.GenerateRecommendFutureOutput.FromString,
        )


class OptionFuturesServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def PortfolioDelta(self, request, context):
    """=========================================================
    期权部分函数文档
    =========================================================
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PortfolioGamma(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PortfolioVega(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PortfolioTheta(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PortfolioRho(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PortfolioVolatility(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PortfolioEarningRate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RetrainDeltaModel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RetrainGammaModel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FitDelta(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FitGamma(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CalOptionAmt(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GenerateRecommendOptionDelta(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GenerateRecommendOptionGamma(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PortfolioBeta(self, request, context):
    """=========================================================
    期货部分函数文档
    =========================================================

    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RetrainBetaModel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FitBeta(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CalFutureAmt(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GenerateRecommendFuture(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_OptionFuturesServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'PortfolioDelta': grpc.unary_unary_rpc_method_handler(
          servicer.PortfolioDelta,
          request_deserializer=option__futures__pb2.PortfolioDeltaInput.FromString,
          response_serializer=option__futures__pb2.PortfolioDeltaOutput.SerializeToString,
      ),
      'PortfolioGamma': grpc.unary_unary_rpc_method_handler(
          servicer.PortfolioGamma,
          request_deserializer=option__futures__pb2.PortfolioGammaInput.FromString,
          response_serializer=option__futures__pb2.PortfolioGammaOutput.SerializeToString,
      ),
      'PortfolioVega': grpc.unary_unary_rpc_method_handler(
          servicer.PortfolioVega,
          request_deserializer=option__futures__pb2.PortfolioVegaInput.FromString,
          response_serializer=option__futures__pb2.PortfolioVegaOutput.SerializeToString,
      ),
      'PortfolioTheta': grpc.unary_unary_rpc_method_handler(
          servicer.PortfolioTheta,
          request_deserializer=option__futures__pb2.PortfolioThetaInput.FromString,
          response_serializer=option__futures__pb2.PortfolioThetaOutput.SerializeToString,
      ),
      'PortfolioRho': grpc.unary_unary_rpc_method_handler(
          servicer.PortfolioRho,
          request_deserializer=option__futures__pb2.PortfolioRhoInput.FromString,
          response_serializer=option__futures__pb2.PortfolioRhoOutput.SerializeToString,
      ),
      'PortfolioVolatility': grpc.unary_unary_rpc_method_handler(
          servicer.PortfolioVolatility,
          request_deserializer=option__futures__pb2.PortfolioVolatilityInput.FromString,
          response_serializer=option__futures__pb2.PortfolioVolatilityOutput.SerializeToString,
      ),
      'PortfolioEarningRate': grpc.unary_unary_rpc_method_handler(
          servicer.PortfolioEarningRate,
          request_deserializer=option__futures__pb2.PortfolioEarningRateInput.FromString,
          response_serializer=option__futures__pb2.PortfolioEarningRateOutput.SerializeToString,
      ),
      'RetrainDeltaModel': grpc.unary_unary_rpc_method_handler(
          servicer.RetrainDeltaModel,
          request_deserializer=option__futures__pb2.RetrainDeltaModelInput.FromString,
          response_serializer=option__futures__pb2.RetrainDeltaModelOutput.SerializeToString,
      ),
      'RetrainGammaModel': grpc.unary_unary_rpc_method_handler(
          servicer.RetrainGammaModel,
          request_deserializer=option__futures__pb2.RetrainGammaModelInput.FromString,
          response_serializer=option__futures__pb2.RetrainGammaModelOutput.SerializeToString,
      ),
      'FitDelta': grpc.unary_unary_rpc_method_handler(
          servicer.FitDelta,
          request_deserializer=option__futures__pb2.FitDeltaInput.FromString,
          response_serializer=option__futures__pb2.FitDeltaOutput.SerializeToString,
      ),
      'FitGamma': grpc.unary_unary_rpc_method_handler(
          servicer.FitGamma,
          request_deserializer=option__futures__pb2.FitGammaInput.FromString,
          response_serializer=option__futures__pb2.FitGammaOutput.SerializeToString,
      ),
      'CalOptionAmt': grpc.unary_unary_rpc_method_handler(
          servicer.CalOptionAmt,
          request_deserializer=option__futures__pb2.CalOptionAmtInput.FromString,
          response_serializer=option__futures__pb2.CalOptionAmtOutput.SerializeToString,
      ),
      'GenerateRecommendOptionDelta': grpc.unary_unary_rpc_method_handler(
          servicer.GenerateRecommendOptionDelta,
          request_deserializer=option__futures__pb2.GenerateRecommendOptionDeltaInput.FromString,
          response_serializer=option__futures__pb2.GenerateRecommendOptionDeltaOutput.SerializeToString,
      ),
      'GenerateRecommendOptionGamma': grpc.unary_unary_rpc_method_handler(
          servicer.GenerateRecommendOptionGamma,
          request_deserializer=option__futures__pb2.GenerateRecommendOptionGammaInput.FromString,
          response_serializer=option__futures__pb2.GenerateRecommendOptionGammaOutput.SerializeToString,
      ),
      'PortfolioBeta': grpc.unary_unary_rpc_method_handler(
          servicer.PortfolioBeta,
          request_deserializer=option__futures__pb2.PortfolioBetaInput.FromString,
          response_serializer=option__futures__pb2.PortfolioBetaOutput.SerializeToString,
      ),
      'RetrainBetaModel': grpc.unary_unary_rpc_method_handler(
          servicer.RetrainBetaModel,
          request_deserializer=option__futures__pb2.RetrainBetaModelInput.FromString,
          response_serializer=option__futures__pb2.RetrainBetaModelOutput.SerializeToString,
      ),
      'FitBeta': grpc.unary_unary_rpc_method_handler(
          servicer.FitBeta,
          request_deserializer=option__futures__pb2.FitBetaInput.FromString,
          response_serializer=option__futures__pb2.FitBetaOutput.SerializeToString,
      ),
      'CalFutureAmt': grpc.unary_unary_rpc_method_handler(
          servicer.CalFutureAmt,
          request_deserializer=option__futures__pb2.CalFutureAmtInput.FromString,
          response_serializer=option__futures__pb2.CalFutureAmtOutput.SerializeToString,
      ),
      'GenerateRecommendFuture': grpc.unary_unary_rpc_method_handler(
          servicer.GenerateRecommendFuture,
          request_deserializer=option__futures__pb2.GenerateRecommendFutureInput.FromString,
          response_serializer=option__futures__pb2.GenerateRecommendFutureOutput.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'OptionFutures', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
