# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: regular_adjustment.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='regular_adjustment.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x18regular_adjustment.proto\"U\n\x17StockLeastPositionInput\x12\x12\n\nstock_code\x18\x01 \x01(\t\x12\x15\n\ruser_position\x18\x02 \x01(\x05\x12\x0f\n\x07setting\x18\x03 \x01(\x05\")\n\x18StockLeastPositionOutput\x12\r\n\x05value\x18\x01 \x01(\x05\"I\n\x14StockVolatilityInput\x12\x12\n\nstock_code\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\x05\x12\x0f\n\x07setting\x18\x03 \x01(\x02\"&\n\x15StockVolatilityOutput\x12\r\n\x05value\x18\x01 \x01(\x08\"Q\n\x10StockChangeInput\x12\x12\n\nstock_code\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\x05\x12\x0b\n\x03top\x18\x03 \x01(\x02\x12\x0e\n\x06\x62ottom\x18\x04 \x01(\x02\"\"\n\x11StockChangeOutput\x12\r\n\x05value\x18\x01 \x01(\x08\"I\n\x14StockMeanReturnInput\x12\x12\n\nstock_code\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\x05\x12\x0f\n\x07setting\x18\x03 \x01(\x02\"&\n\x15StockMeanReturnOutput\x12\r\n\x05value\x18\x01 \x01(\x08\x32\xa0\x02\n\x11RegularAdjustment\x12K\n\x12StockLeastPosition\x12\x18.StockLeastPositionInput\x1a\x19.StockLeastPositionOutput\"\x00\x12\x42\n\x0fStockVolatility\x12\x15.StockVolatilityInput\x1a\x16.StockVolatilityOutput\"\x00\x12\x36\n\x0bStockChange\x12\x11.StockChangeInput\x1a\x12.StockChangeOutput\"\x00\x12\x42\n\x0fStockMeanReturn\x12\x15.StockMeanReturnInput\x1a\x16.StockMeanReturnOutput\"\x00\x62\x06proto3')
)




_STOCKLEASTPOSITIONINPUT = _descriptor.Descriptor(
  name='StockLeastPositionInput',
  full_name='StockLeastPositionInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stock_code', full_name='StockLeastPositionInput.stock_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_position', full_name='StockLeastPositionInput.user_position', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='setting', full_name='StockLeastPositionInput.setting', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=113,
)


_STOCKLEASTPOSITIONOUTPUT = _descriptor.Descriptor(
  name='StockLeastPositionOutput',
  full_name='StockLeastPositionOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='StockLeastPositionOutput.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=156,
)


_STOCKVOLATILITYINPUT = _descriptor.Descriptor(
  name='StockVolatilityInput',
  full_name='StockVolatilityInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stock_code', full_name='StockVolatilityInput.stock_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='StockVolatilityInput.time', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='setting', full_name='StockVolatilityInput.setting', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=231,
)


_STOCKVOLATILITYOUTPUT = _descriptor.Descriptor(
  name='StockVolatilityOutput',
  full_name='StockVolatilityOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='StockVolatilityOutput.value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=271,
)


_STOCKCHANGEINPUT = _descriptor.Descriptor(
  name='StockChangeInput',
  full_name='StockChangeInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stock_code', full_name='StockChangeInput.stock_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='StockChangeInput.time', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='top', full_name='StockChangeInput.top', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bottom', full_name='StockChangeInput.bottom', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=354,
)


_STOCKCHANGEOUTPUT = _descriptor.Descriptor(
  name='StockChangeOutput',
  full_name='StockChangeOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='StockChangeOutput.value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=356,
  serialized_end=390,
)


_STOCKMEANRETURNINPUT = _descriptor.Descriptor(
  name='StockMeanReturnInput',
  full_name='StockMeanReturnInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stock_code', full_name='StockMeanReturnInput.stock_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='StockMeanReturnInput.time', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='setting', full_name='StockMeanReturnInput.setting', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=392,
  serialized_end=465,
)


_STOCKMEANRETURNOUTPUT = _descriptor.Descriptor(
  name='StockMeanReturnOutput',
  full_name='StockMeanReturnOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='StockMeanReturnOutput.value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=467,
  serialized_end=505,
)

DESCRIPTOR.message_types_by_name['StockLeastPositionInput'] = _STOCKLEASTPOSITIONINPUT
DESCRIPTOR.message_types_by_name['StockLeastPositionOutput'] = _STOCKLEASTPOSITIONOUTPUT
DESCRIPTOR.message_types_by_name['StockVolatilityInput'] = _STOCKVOLATILITYINPUT
DESCRIPTOR.message_types_by_name['StockVolatilityOutput'] = _STOCKVOLATILITYOUTPUT
DESCRIPTOR.message_types_by_name['StockChangeInput'] = _STOCKCHANGEINPUT
DESCRIPTOR.message_types_by_name['StockChangeOutput'] = _STOCKCHANGEOUTPUT
DESCRIPTOR.message_types_by_name['StockMeanReturnInput'] = _STOCKMEANRETURNINPUT
DESCRIPTOR.message_types_by_name['StockMeanReturnOutput'] = _STOCKMEANRETURNOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StockLeastPositionInput = _reflection.GeneratedProtocolMessageType('StockLeastPositionInput', (_message.Message,), {
  'DESCRIPTOR' : _STOCKLEASTPOSITIONINPUT,
  '__module__' : 'regular_adjustment_pb2'
  # @@protoc_insertion_point(class_scope:StockLeastPositionInput)
  })
_sym_db.RegisterMessage(StockLeastPositionInput)

StockLeastPositionOutput = _reflection.GeneratedProtocolMessageType('StockLeastPositionOutput', (_message.Message,), {
  'DESCRIPTOR' : _STOCKLEASTPOSITIONOUTPUT,
  '__module__' : 'regular_adjustment_pb2'
  # @@protoc_insertion_point(class_scope:StockLeastPositionOutput)
  })
_sym_db.RegisterMessage(StockLeastPositionOutput)

StockVolatilityInput = _reflection.GeneratedProtocolMessageType('StockVolatilityInput', (_message.Message,), {
  'DESCRIPTOR' : _STOCKVOLATILITYINPUT,
  '__module__' : 'regular_adjustment_pb2'
  # @@protoc_insertion_point(class_scope:StockVolatilityInput)
  })
_sym_db.RegisterMessage(StockVolatilityInput)

StockVolatilityOutput = _reflection.GeneratedProtocolMessageType('StockVolatilityOutput', (_message.Message,), {
  'DESCRIPTOR' : _STOCKVOLATILITYOUTPUT,
  '__module__' : 'regular_adjustment_pb2'
  # @@protoc_insertion_point(class_scope:StockVolatilityOutput)
  })
_sym_db.RegisterMessage(StockVolatilityOutput)

StockChangeInput = _reflection.GeneratedProtocolMessageType('StockChangeInput', (_message.Message,), {
  'DESCRIPTOR' : _STOCKCHANGEINPUT,
  '__module__' : 'regular_adjustment_pb2'
  # @@protoc_insertion_point(class_scope:StockChangeInput)
  })
_sym_db.RegisterMessage(StockChangeInput)

StockChangeOutput = _reflection.GeneratedProtocolMessageType('StockChangeOutput', (_message.Message,), {
  'DESCRIPTOR' : _STOCKCHANGEOUTPUT,
  '__module__' : 'regular_adjustment_pb2'
  # @@protoc_insertion_point(class_scope:StockChangeOutput)
  })
_sym_db.RegisterMessage(StockChangeOutput)

StockMeanReturnInput = _reflection.GeneratedProtocolMessageType('StockMeanReturnInput', (_message.Message,), {
  'DESCRIPTOR' : _STOCKMEANRETURNINPUT,
  '__module__' : 'regular_adjustment_pb2'
  # @@protoc_insertion_point(class_scope:StockMeanReturnInput)
  })
_sym_db.RegisterMessage(StockMeanReturnInput)

StockMeanReturnOutput = _reflection.GeneratedProtocolMessageType('StockMeanReturnOutput', (_message.Message,), {
  'DESCRIPTOR' : _STOCKMEANRETURNOUTPUT,
  '__module__' : 'regular_adjustment_pb2'
  # @@protoc_insertion_point(class_scope:StockMeanReturnOutput)
  })
_sym_db.RegisterMessage(StockMeanReturnOutput)



_REGULARADJUSTMENT = _descriptor.ServiceDescriptor(
  name='RegularAdjustment',
  full_name='RegularAdjustment',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=508,
  serialized_end=796,
  methods=[
  _descriptor.MethodDescriptor(
    name='StockLeastPosition',
    full_name='RegularAdjustment.StockLeastPosition',
    index=0,
    containing_service=None,
    input_type=_STOCKLEASTPOSITIONINPUT,
    output_type=_STOCKLEASTPOSITIONOUTPUT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StockVolatility',
    full_name='RegularAdjustment.StockVolatility',
    index=1,
    containing_service=None,
    input_type=_STOCKVOLATILITYINPUT,
    output_type=_STOCKVOLATILITYOUTPUT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StockChange',
    full_name='RegularAdjustment.StockChange',
    index=2,
    containing_service=None,
    input_type=_STOCKCHANGEINPUT,
    output_type=_STOCKCHANGEOUTPUT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StockMeanReturn',
    full_name='RegularAdjustment.StockMeanReturn',
    index=3,
    containing_service=None,
    input_type=_STOCKMEANRETURNINPUT,
    output_type=_STOCKMEANRETURNOUTPUT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REGULARADJUSTMENT)

DESCRIPTOR.services_by_name['RegularAdjustment'] = _REGULARADJUSTMENT

# @@protoc_insertion_point(module_scope)
