# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stocks.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stocks.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n\037com.example.ffbackend.rpc.protoB\013StocksProto'),
  serialized_pb=_b('\n\x0cstocks.proto\"\x13\n\x11GetAllStocksInput\"#\n\x12GetAllStocksOutput\x12\r\n\x05value\x18\x01 \x03(\t2C\n\x06Stocks\x12\x39\n\x0cGetAllStocks\x12\x12.GetAllStocksInput\x1a\x13.GetAllStocksOutput\"\x00\x42.\n\x1f\x63om.example.ffbackend.rpc.protoB\x0bStocksProtob\x06proto3')
)




_GETALLSTOCKSINPUT = _descriptor.Descriptor(
  name='GetAllStocksInput',
  full_name='GetAllStocksInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=35,
)


_GETALLSTOCKSOUTPUT = _descriptor.Descriptor(
  name='GetAllStocksOutput',
  full_name='GetAllStocksOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='GetAllStocksOutput.value', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=72,
)

DESCRIPTOR.message_types_by_name['GetAllStocksInput'] = _GETALLSTOCKSINPUT
DESCRIPTOR.message_types_by_name['GetAllStocksOutput'] = _GETALLSTOCKSOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetAllStocksInput = _reflection.GeneratedProtocolMessageType('GetAllStocksInput', (_message.Message,), dict(
  DESCRIPTOR = _GETALLSTOCKSINPUT,
  __module__ = 'stocks_pb2'
  # @@protoc_insertion_point(class_scope:GetAllStocksInput)
  ))
_sym_db.RegisterMessage(GetAllStocksInput)

GetAllStocksOutput = _reflection.GeneratedProtocolMessageType('GetAllStocksOutput', (_message.Message,), dict(
  DESCRIPTOR = _GETALLSTOCKSOUTPUT,
  __module__ = 'stocks_pb2'
  # @@protoc_insertion_point(class_scope:GetAllStocksOutput)
  ))
_sym_db.RegisterMessage(GetAllStocksOutput)


DESCRIPTOR._options = None

_STOCKS = _descriptor.ServiceDescriptor(
  name='Stocks',
  full_name='Stocks',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=74,
  serialized_end=141,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAllStocks',
    full_name='Stocks.GetAllStocks',
    index=0,
    containing_service=None,
    input_type=_GETALLSTOCKSINPUT,
    output_type=_GETALLSTOCKSOUTPUT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STOCKS)

DESCRIPTOR.services_by_name['Stocks'] = _STOCKS

# @@protoc_insertion_point(module_scope)
