# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: style_factor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='style_factor.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12style_factor.proto\"/\n\x0cGetSizeInput\x12\x0f\n\x07ts_code\x18\x01 \x01(\t\x12\x0e\n\x06\x66ields\x18\x02 \x01(\t\"\x1e\n\rGetSizeOutput\x12\r\n\x05value\x18\x01 \x01(\x02\"#\n\x10GetMomentumInput\x12\x0f\n\x07ts_code\x18\x01 \x01(\t\"\"\n\x11GetMomentumOutput\x12\r\n\x05value\x18\x01 \x01(\x02\"*\n\x14GetBookToMarketInput\x12\x12\n\nstock_code\x18\x01 \x01(\t\"&\n\x15GetBookToMarketOutput\x12\r\n\x05value\x18\x01 \x01(\x02\"\'\n\x11GetLiquidityInput\x12\x12\n\nstock_code\x18\x01 \x01(\t\"#\n\x12GetLiquidityOutput\x12\r\n\x05value\x18\x01 \x01(\x02\x32\xf0\x01\n\x0bStyleFactor\x12*\n\x07GetSize\x12\r.GetSizeInput\x1a\x0e.GetSizeOutput\"\x00\x12\x36\n\x0bGetMomentum\x12\x11.GetMomentumInput\x1a\x12.GetMomentumOutput\"\x00\x12\x42\n\x0fGetBookToMarket\x12\x15.GetBookToMarketInput\x1a\x16.GetBookToMarketOutput\"\x00\x12\x39\n\x0cGetLiquidity\x12\x12.GetLiquidityInput\x1a\x13.GetLiquidityOutput\"\x00\x62\x06proto3')
)




_GETSIZEINPUT = _descriptor.Descriptor(
  name='GetSizeInput',
  full_name='GetSizeInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ts_code', full_name='GetSizeInput.ts_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fields', full_name='GetSizeInput.fields', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=69,
)


_GETSIZEOUTPUT = _descriptor.Descriptor(
  name='GetSizeOutput',
  full_name='GetSizeOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='GetSizeOutput.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=101,
)


_GETMOMENTUMINPUT = _descriptor.Descriptor(
  name='GetMomentumInput',
  full_name='GetMomentumInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ts_code', full_name='GetMomentumInput.ts_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=138,
)


_GETMOMENTUMOUTPUT = _descriptor.Descriptor(
  name='GetMomentumOutput',
  full_name='GetMomentumOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='GetMomentumOutput.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=174,
)


_GETBOOKTOMARKETINPUT = _descriptor.Descriptor(
  name='GetBookToMarketInput',
  full_name='GetBookToMarketInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stock_code', full_name='GetBookToMarketInput.stock_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=218,
)


_GETBOOKTOMARKETOUTPUT = _descriptor.Descriptor(
  name='GetBookToMarketOutput',
  full_name='GetBookToMarketOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='GetBookToMarketOutput.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=220,
  serialized_end=258,
)


_GETLIQUIDITYINPUT = _descriptor.Descriptor(
  name='GetLiquidityInput',
  full_name='GetLiquidityInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stock_code', full_name='GetLiquidityInput.stock_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=299,
)


_GETLIQUIDITYOUTPUT = _descriptor.Descriptor(
  name='GetLiquidityOutput',
  full_name='GetLiquidityOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='GetLiquidityOutput.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=301,
  serialized_end=336,
)

DESCRIPTOR.message_types_by_name['GetSizeInput'] = _GETSIZEINPUT
DESCRIPTOR.message_types_by_name['GetSizeOutput'] = _GETSIZEOUTPUT
DESCRIPTOR.message_types_by_name['GetMomentumInput'] = _GETMOMENTUMINPUT
DESCRIPTOR.message_types_by_name['GetMomentumOutput'] = _GETMOMENTUMOUTPUT
DESCRIPTOR.message_types_by_name['GetBookToMarketInput'] = _GETBOOKTOMARKETINPUT
DESCRIPTOR.message_types_by_name['GetBookToMarketOutput'] = _GETBOOKTOMARKETOUTPUT
DESCRIPTOR.message_types_by_name['GetLiquidityInput'] = _GETLIQUIDITYINPUT
DESCRIPTOR.message_types_by_name['GetLiquidityOutput'] = _GETLIQUIDITYOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetSizeInput = _reflection.GeneratedProtocolMessageType('GetSizeInput', (_message.Message,), {
  'DESCRIPTOR' : _GETSIZEINPUT,
  '__module__' : 'style_factor_pb2'
  # @@protoc_insertion_point(class_scope:GetSizeInput)
  })
_sym_db.RegisterMessage(GetSizeInput)

GetSizeOutput = _reflection.GeneratedProtocolMessageType('GetSizeOutput', (_message.Message,), {
  'DESCRIPTOR' : _GETSIZEOUTPUT,
  '__module__' : 'style_factor_pb2'
  # @@protoc_insertion_point(class_scope:GetSizeOutput)
  })
_sym_db.RegisterMessage(GetSizeOutput)

GetMomentumInput = _reflection.GeneratedProtocolMessageType('GetMomentumInput', (_message.Message,), {
  'DESCRIPTOR' : _GETMOMENTUMINPUT,
  '__module__' : 'style_factor_pb2'
  # @@protoc_insertion_point(class_scope:GetMomentumInput)
  })
_sym_db.RegisterMessage(GetMomentumInput)

GetMomentumOutput = _reflection.GeneratedProtocolMessageType('GetMomentumOutput', (_message.Message,), {
  'DESCRIPTOR' : _GETMOMENTUMOUTPUT,
  '__module__' : 'style_factor_pb2'
  # @@protoc_insertion_point(class_scope:GetMomentumOutput)
  })
_sym_db.RegisterMessage(GetMomentumOutput)

GetBookToMarketInput = _reflection.GeneratedProtocolMessageType('GetBookToMarketInput', (_message.Message,), {
  'DESCRIPTOR' : _GETBOOKTOMARKETINPUT,
  '__module__' : 'style_factor_pb2'
  # @@protoc_insertion_point(class_scope:GetBookToMarketInput)
  })
_sym_db.RegisterMessage(GetBookToMarketInput)

GetBookToMarketOutput = _reflection.GeneratedProtocolMessageType('GetBookToMarketOutput', (_message.Message,), {
  'DESCRIPTOR' : _GETBOOKTOMARKETOUTPUT,
  '__module__' : 'style_factor_pb2'
  # @@protoc_insertion_point(class_scope:GetBookToMarketOutput)
  })
_sym_db.RegisterMessage(GetBookToMarketOutput)

GetLiquidityInput = _reflection.GeneratedProtocolMessageType('GetLiquidityInput', (_message.Message,), {
  'DESCRIPTOR' : _GETLIQUIDITYINPUT,
  '__module__' : 'style_factor_pb2'
  # @@protoc_insertion_point(class_scope:GetLiquidityInput)
  })
_sym_db.RegisterMessage(GetLiquidityInput)

GetLiquidityOutput = _reflection.GeneratedProtocolMessageType('GetLiquidityOutput', (_message.Message,), {
  'DESCRIPTOR' : _GETLIQUIDITYOUTPUT,
  '__module__' : 'style_factor_pb2'
  # @@protoc_insertion_point(class_scope:GetLiquidityOutput)
  })
_sym_db.RegisterMessage(GetLiquidityOutput)



_STYLEFACTOR = _descriptor.ServiceDescriptor(
  name='StyleFactor',
  full_name='StyleFactor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=339,
  serialized_end=579,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSize',
    full_name='StyleFactor.GetSize',
    index=0,
    containing_service=None,
    input_type=_GETSIZEINPUT,
    output_type=_GETSIZEOUTPUT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetMomentum',
    full_name='StyleFactor.GetMomentum',
    index=1,
    containing_service=None,
    input_type=_GETMOMENTUMINPUT,
    output_type=_GETMOMENTUMOUTPUT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetBookToMarket',
    full_name='StyleFactor.GetBookToMarket',
    index=2,
    containing_service=None,
    input_type=_GETBOOKTOMARKETINPUT,
    output_type=_GETBOOKTOMARKETOUTPUT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetLiquidity',
    full_name='StyleFactor.GetLiquidity',
    index=3,
    containing_service=None,
    input_type=_GETLIQUIDITYINPUT,
    output_type=_GETLIQUIDITYOUTPUT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STYLEFACTOR)

DESCRIPTOR.services_by_name['StyleFactor'] = _STYLEFACTOR

# @@protoc_insertion_point(module_scope)
