# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tail_risk.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tail_risk.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0ftail_risk.proto2\n\n\x08TailRiskb\x06proto3')
)



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_TAILRISK = _descriptor.ServiceDescriptor(
  name='TailRisk',
  full_name='TailRisk',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=19,
  serialized_end=29,
  methods=[
])
_sym_db.RegisterServiceDescriptor(_TAILRISK)

DESCRIPTOR.services_by_name['TailRisk'] = _TAILRISK

# @@protoc_insertion_point(module_scope)
